version: '3.8'

services:
  facebook-ads-scraper:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - HEADLESS=true
    volumes:
      - ./data:/app/data
      - ./cache:/app/cache
      - ./logs:/app/logs
    restart: unless-stopped
    
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped